#This function reads and parses the movie details from individual movie pages
#INPUT:
#  - CSV file "mainPageData.csv" generated by "ExtractMainPage.R"
#  
#
#OUTPUT:
#   Create a new file "movieDetails.csv"
#   For each movie in the input file 
#   Add additional columns:
#     - DurationMins
#     - Genre1
#     - Genre2 ( "" if not exists)
#     - Genre3 ( "" if not exists)
#     - NumIMDBUserReviews
#     - NumIMDBCriticReviews
#     - DirectorName
#     - DirectorID
#     - DirectorURL
#     - Star1Name
#     - Star1ID
#     - Star1URL
#     - Star2Name
#     - Star2ID
#     - Star2URL
#     - Star3Name
#     - Star3ID
#     - Star3URL
#     - BoxOfficeBudget
#     - BoxOfficeOpeningWeekend
#     - BoxOfficeGross
#  
#     +
# 
#  - Pre Existing Columns:
#     - MovieID
#     - MovieURL
#     - MovieTitle
#     - ReleaseYear
#     - MovieRating
#     - MovieNumUserRatings
#     - ReleaseDateUS

extractMovieDetails <- function(inFile){}