#This function reads and parses the award details from individual award pages
#INPUT:
#  - CSV file "movieDetails.csv" generated by "ExtractMovieDetails.R"
#  
#
#OUTPUT:
#   Create a new file "movieDetails-withAwards.csv"
#   For each movie in the input file 
#   Add additional columns:
#     - AwardsPageURL (**** DON'T NEED THIS ?)
#     - NumOscars  (***This is the Response Variable***)
# 
#  - Pre Existing Columns:
#     - MovieID
#     - MovieURL
#     - MovieTitle
#     - ReleaseYear
#     - IsRateOptionEnabled
#     - MovieRating
#     - MovieNumUserRatings
#     - ReleaseDateUS
#     - DurationMins
#     - Genre1
#     - Genre2 ( "" if not exists)
#     - Genre3 ( "" if not exists)
#     - NumIMDBUserReviews
#     - NumIMDBCriticReviews
#     - DirectorName
#     - DirectorID
#     - DirectorURL
#     - Star1Name
#     - Star1ID
#     - Star1URL
#     - Star2Name ( "" if not exists)
#     - Star2ID ( "" if not exists)
#     - Star2URL ( "" if not exists)
#     - Star3Name ( "" if not exists)
#     - Star3ID ( "" if not exists)
#     - Star3URL ( "" if not exists)
#     - BoxOfficeBudget
#     - BoxOfficeOpeningWeekend
#     - BoxOfficeGross

library(rvest)
library(magrittr)
library(stringr)


extractMovieDetails <- function(inFile){
  #change to actual file "inFile" once all modules completed
  mainPageData <- read.csv("../../data/dummy-mainPageData.csv",stringsAsFactors = FALSE)
  urls <-  mainPageData$MovieURL
  x <- sapply(urls,extractOscarWonNr)
  x <- t(x)
  colnames(x) <- c("NumOscars")
  
  finalDF <- cbind(mainPageData,x)
  write.csv(finalDF,file = "../../data/movieDetails.csv",row.names = FALSE)
}

extractOscarWonNr <- function(url){
  source.page <- read_html(url)
  
  #NumOscarWins
  NumOscarWins <- source.page %>% 
    html_nodes("#titleAwardsRanks :nth-child(1)") %>%  
    html_text() %>% 
    str_replace_all("[^0-9]","")
  
  returnVector <- c(NumOscarWins)  
  return(returnVector)
}

#TODO: TEST CODE: Remove test code on completion
extractOscarWonNr(NULL)
