# This is a change by Michael.

#This function reads and parses the award details from individual award pages
#INPUT:
#  - CSV file "movieDetails.csv" generated by "ExtractMovieDetails.R"
#  
#
#OUTPUT:
#   Create a new file "movieDetails-withAwards.csv"
#   For each movie in the input file 
#   Add additional columns:
#     - AwardsPageURL
#     - NumOscars  (***This is the Response Variable***)
# 
#  - Pre Existing Columns:
#     - MovieID
#     - MovieURL
#     - MovieTitle
#     - ReleaseYear
#     - IsRateOptionEnabled
#     - MovieRating
#     - MovieNumUserRatings
#     - ReleaseDateUS
#     - DurationMins
#     - Genre1
#     - Genre2 ( "" if not exists)
#     - Genre3 ( "" if not exists)
#     - NumIMDBUserReviews
#     - NumIMDBCriticReviews
#     - DirectorName
#     - DirectorID
#     - DirectorURL
#     - Star1Name
#     - Star1ID
#     - Star1URL
#     - Star2Name ( "" if not exists)
#     - Star2ID ( "" if not exists)
#     - Star2URL ( "" if not exists)
#     - Star3Name ( "" if not exists)
#     - Star3ID ( "" if not exists)
#     - Star3URL ( "" if not exists)
#     - BoxOfficeBudget
#     - BoxOfficeOpeningWeekend
#     - BoxOfficeGross

extractMovieDetails <- function(inFile){}