# This file contains the function extractMovieDetails()
# 
# This function reads and parses the movie details from individual movie pages
# INPUT:
#  - DataFrame "mainPageData" generated by "ExtractMainPage.R"
#  
#
# OUTPUT:
#   Create a new file "movieDetails.csv"
#   For each movie in the input file 
#   Add additional columns:
#     - DurationMins
#     - MovieRating
#     - MovieNumUserRatings
#     - ReleaseYear
#     - ReleaseDateUS
#     - Genre1
#     - Genre2 
#     - Genre3 
#     - NumIMDBUserReviews
#     - NumIMDBCriticReviews
#     - DirectorName
#     - DirectorID
#     - DirectorURL
#     - Star1Name
#     - Star1ID
#     - Star1URL
#     - Star2Name
#     - Star2ID
#     - Star2URL
#     - Star3Name
#     - Star3ID
#     - Star3URL
#     - BoxOfficeBudget
#     - BoxOfficeBudgetCurr
#     - BoxOfficeOpeningWeekend
#     - BoxOfficeOpeningWeekendCurr
#     - BoxOfficeGross
#     - BoxOfficeGrossCurr
#     - Number of Oscars
#  
#     +
# 
#  - Pre Existing Columns:
#     - MovieID
#     - MovieURL
#     - MovieTitle
#
###########################################################################

#Install and load required libraries

# install.packages("rvest")
# install.packages("magrittr")
# install.packages("stringr")

library(rvest)
library(magrittr)
library(stringr)

###########################################################################

extractMovieDetails <- function(mainPageData){
  
  urls <-  as.character(mainPageData$MovieURL)
  
  if(file.exists("../../data/x1.R")){
    load("../../data/x1.R")
  }
  else{
    x1 <- sapply((1:1000),extractSingleMovieDetail,urls=urls)
    save(x1,file="../../data/x1.R")
  }
  
  if(file.exists("../../data/x2.R")){
    load("../../data/x2.R")
  }
  else{
    x2 <- sapply((1001:2000),extractSingleMovieDetail,urls=urls)
    save(x2,file="../../data/x2.R")
  }
  
  if(file.exists("../../data/x3.R")){
    load("../../data/x3.R")
  }
  else{
    x3 <- sapply((2001:3000),extractSingleMovieDetail,urls=urls)
    save(x3,file="../../data/x3.R")
  }
  
  if(file.exists("../../data/x4.R")){
    load("../../data/x4.R")
  }
  else{
    x4 <- sapply((3001:4000),extractSingleMovieDetail,urls=urls)
    save(x4,file="../../data/x4.R")
  }
  
  if(file.exists("../../data/x5.R")){
    load("../../data/x5.R")
  }
  else{
    x5 <- sapply((4001:5000),extractSingleMovieDetail,urls=urls)
    save(x5,file="../../data/x5.R")
  }
  
  if(file.exists("../../data/x6.R")){
    load("../../data/x6.R")
  }
  else{
    x6 <- sapply((5001:6000),extractSingleMovieDetail,urls=urls)
    save(x6,file="../../data/x6.R")
  }
  
  if(file.exists("../../data/x7.R")){
    load("../../data/x7.R")
  }
  else{
    x7 <- sapply((6001:7000),extractSingleMovieDetail,urls=urls)
    save(x7,file="../../data/x7.R")
  }
  
  if(file.exists("../../data/x8.R")){
    load("../../data/x8.R")
  }
  else{
    x8 <- sapply((7001:8000),extractSingleMovieDetail,urls=urls)
    save(x8,file="../../data/x8.R")
  }
  
  if(file.exists("../../data/x9.R")){
    load("../../data/x9.R")
  }
  else{
    x9 <- sapply((8001:9000),extractSingleMovieDetail,urls=urls)
    save(x9,file="../../data/x9.R")
  }
  
  if(file.exists("../../data/x10.R")){
    load("../../data/x10.R")
  }
  else{
    x10 <- sapply((9001:length(urls)),extractSingleMovieDetail,urls=urls)
    save(x10,file="../../data/x10.R")
  }
  
  x <- cbind(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10)
  
  x <- t(x)
  
  colnames(x) <- c("ReleaseYear", "IMDBRating","NumberOfUsersRated","DurationMins", "ReleaseDate", "Genre1","Genre2","Genre3",
                   "NumIMDBCriticReviews",
                   "DirectorName","DirectorID","DirectorURL","Star1Name","Star1ID","Star1URL","Star2Name",
                   "Star2ID","Star2URL","Star3Name","Star3ID","Star3URL","BoxOfficeBudget",
                   "BoxOfficeBudgetCurr","BoxOfficeOpeningWeekend","BoxOfficeOpeningWeekendCurr",
                   "BoxOfficeGross","BoxOfficeGrossCurr","NumberOfOscars")
  
  mainPageData <- cbind(mainPageData,x)
  mainPageData <- as.data.frame(mainPageData)
  return(mainPageData)
}

###############################################################################################

extractSingleMovieDetail <- function(i,urls){
  print(i)
  url <- urls[i]
  
  source.page <- read_html(url)
  #release year
  release_yr <- source.page %>% 
    html_nodes(".header .nobr") %>%  
    html_text() %>%
    str_replace_all("[^0-9]","")
  release_yr <- ifelse(length(release_yr)<1,NA,release_yr)
  
  #movie rating
  movie_rating <- source.page %>% 
    html_nodes("strong span") %>%  
    html_text()
  movie_rating <- ifelse(length(movie_rating)<1,NA,movie_rating)
  
  #number of users who rated movie
  MovieNumUserRatings <- source.page %>% 
    html_nodes(".star-box-details a:nth-child(3) span") %>%  
    html_text() %>%
    str_replace_all("[^0-9]","")
  MovieNumUserRatings <- ifelse(length(MovieNumUserRatings)<1,NA,MovieNumUserRatings)
  
  #duration
  duration_mins <- source.page %>% 
    html_nodes("#overview-top time") %>%  
    html_text() %>%
    str_replace_all("[^0-9]","")
  duration_mins <- ifelse(length(duration_mins)<1,NA,duration_mins)

  #ReleaseDate
  ReleaseDate <- source.page %>% 
    html_nodes(".infobar .nobr a") %>%  
    html_text()
  ReleaseDate <- ifelse(length(ReleaseDate)<1,NA,ReleaseDate)
  
  #genres
  genres <- source.page %>% 
    html_nodes(".infobar .itemprop") %>%  
    html_text()
  genre1 <- genres[1]
  genre2 <- genres[2]
  genre3 <- genres[3]
  
  #NumImdbCriticReviews
  numImdbCriticReviews <- source.page %>% 
    html_nodes(".star-box-details a:nth-child(8) span") %>%  
    html_text() %>% 
    str_replace_all("[^0-9]","")
  numImdbCriticReviews <- ifelse(length(numImdbCriticReviews)<1,NA,numImdbCriticReviews)
  
  #Directors
  #detect Director Node
  directorNode7 <- source.page %>% 
    html_nodes("#overview-top .txt-block:nth-child(7)") %>%  
    html_text()
  if(grepl(pattern="Director",x=directorNode7)){
    css_node <- "#overview-top :nth-child(7) .itemprop"
  }  else{
    directorNode8 <- source.page %>% 
      html_nodes("#overview-top .txt-block:nth-child(8)") %>%  
      html_text()
    if(grepl(pattern="Director",x=directorNode8)){
      css_node <- "#overview-top :nth-child(8) .itemprop"
    }else{
      css_node <- "#overview-top :nth-child(9) .itemprop"
    }
  }
  
  #DirectorName
  directorName <- source.page %>% 
    html_nodes("#overview-top :nth-child(8) .itemprop") %>%  
    html_text()
  directorName <- ifelse(length(directorName)<1,NA,directorName)
  
  #DirectorURL and DirectorID
  directorURL <- source.page %>% 
    html_nodes("#overview-top :nth-child(8) a") %>%  
    html_attr("href") %>%
    str_replace_all("\\?.*","")
  directorURL <- ifelse(is.na(directorURL[2]),NA,paste0('http://imdb.com',directorURL[2]))
  directorID <- str_replace_all(directorURL,'http://www.imdb.com/name/|/$',"")
  
  #Stars
  #detect stars node
  starsNode8 <- source.page %>% 
    html_nodes("#overview-top .txt-block:nth-child(8)") %>%  
    html_text()
  if(grepl(pattern="Stars:",x=starsNode8)){
    css_node <- "#overview-top :nth-child(8) .itemprop"
  }  else{
    starsNode9 <- source.page %>% 
      html_nodes("#overview-top .txt-block:nth-child(9)") %>%  
      html_text()
      if(grepl(pattern="Stars:",x=starsNode9)){
        css_node <- "#overview-top :nth-child(9) .itemprop"
      }else{
        css_node <- "#overview-top :nth-child(10) .itemprop"
      }
  }
    
  stars <- source.page %>% 
    html_nodes(css_node) %>%  
    html_text()
  starsURLs <- source.page %>% 
    html_nodes("css_node") %>%  
    html_attr("href") %>%
    str_replace_all("\\?.*","")
  starsURLs <- starsURLs[1:3]
  
  starsIds <- str_replace_all(starsURLs,'/name/|/$',"")
  star1Name <-  stars[1]
  star1Id <-  starsIds[1]
  star1URL <-  ifelse(is.na(starsURLs[1]),NA,paste0('http://www.imdb.com',starsURLs[1]))
  star2Name <-  stars[2]
  star2Id <-  starsIds[2]
  star2URL <-  ifelse(is.na(starsURLs[2]),NA,paste0('http://www.imdb.com',starsURLs[2]))
  star3Name <-  stars[3]
  star3Id <-  starsIds[3]
  star3URL <-  ifelse(is.na(starsURLs[3]),NA,paste0('http://www.imdb.com',starsURLs[3]))
  
  #Box Office Budget
  budget <- source.page %>% 
    html_nodes("#titleDetails :nth-child(11)") %>%  
    html_text()
  budget <- ifelse(length(budget)<1,NA,budget)
  
  #detect if budget is usd
  isUSD <- grepl("^\\\n\\s*Budget:\\s*\\$[0-9,]*.*$",budget)
  budgetCurr <- NA
  if(length(isUSD)==1 && isUSD){
    budgetCurr <- "USD"
    budget <- str_replace_all(budget,"(\\\n\\s*Budget:\\s*\\$)([0-9,]*)((.|\\n)*)","\\2")
    budget <- str_replace_all(budget,"[^0-9]","")
  }
  
  #Opening Weekend
  openweekend <- source.page %>% 
    html_nodes("#titleDetails :nth-child(12)") %>%  
    html_text()
  openweekend <- ifelse(length(openweekend)<1,NA,openweekend)
  
  #detect if budget is usd
  openweekendCurr <- NA 
  isUSD <- grepl("^\\\n\\s*Opening Weekend:\\s*\\$[0-9,]*.*$",openweekend)
  if(length(isUSD)==1 && isUSD){
    openweekendCurr <- "USD"
    openweekend <- str_replace_all(openweekend,"(\\\n\\s*Opening Weekend:\\s*\\$)([0-9,]*)((.|\\n)*)","\\2")
    openweekend <- str_replace_all(openweekend,"[^0-9]","")
  }
  
  #Gross
  gross <- source.page %>% 
    html_nodes("#titleDetails :nth-child(13)") %>%  
    html_text()
  gross <- ifelse(length(gross)<1,NA,gross)
  
  #detect if gross is usd
  grossCurr <- "NA" 
  isUSD <- grepl("^\\\n\\s*Gross:\\s*\\$[0-9,]*.*$",gross)
  if(length(isUSD)==1 && isUSD){
    grossCurr <- "USD"
    gross <- str_replace_all(gross,"(\\\n\\s*Gross:\\s*\\$)([0-9,]*)((.|\\n)*)","\\2")
    gross <- str_replace_all(gross,"[^0-9]","")
  }
  
  
  #NumOscarWins
  numOscarWins <- source.page %>% 
    html_nodes("#titleAwardsRanks b") %>%  
    html_text() %>% 
    str_replace_all("[^0-9]","")
  if(length(numOscarWins)==0){
    numOscarWins <- 0
  } else{
    numOscarWins <- c(as.numeric(numOscarWins))
  }
  
  returnVector <- c(release_yr, movie_rating, MovieNumUserRatings, duration_mins,ReleaseDate,genre1,genre2,genre3,numImdbCriticReviews,
                    directorName,directorID,directorURL,star1Name,star1Id,star1URL,star2Name,
                    star2Id,star2URL,star3Name,star3Id,star3URL,budget,budgetCurr,openweekend,
                    openweekendCurr,gross,grossCurr,numOscarWins)  
  return(returnVector)
}

