# This file contains the function extractMovieDetails()
# 
# This function reads and parses the movie details from individual movie pages
# INPUT:
#  - DataFrame "mainPageData" generated by "ExtractMainPage.R"
#  
#
# OUTPUT:
#   Create a new file "movieDetails.csv"
#   For each movie in the input file 
#   Add additional columns:

#   "MovieURL","ReleaseYear", "IMDBRating","NumberOfUsersRated","NumberOfCriticsRated",
#   "DurationMins","AspectRatio",
#   "MPAARating","Country","Language","ReleaseDate","Genre1","Genre2","Genre3",
#   "DirectorName","DirectorID","DirectorURL","Star1Name","Star1ID","Star1URL",
#   "Star2Name","Star2ID","Star2URL","Star3Name","Star3ID","Star3URL",
#   "BoxOfficeBudget","BoxOfficeBudgetCurr","BoxOfficeOpeningWeekend","BoxOfficeOpeningWeekendCurr",
#   "BoxOfficeGross","BoxOfficeGrossCurr","NumberOfOscars"  
#     +
# 
#  - Pre Existing Columns:
#     - MovieID
#     - MovieURL
#     - MovieTitle
#
###########################################################################

#Install and load required libraries

# install.packages("rvest")
# install.packages("magrittr")
# install.packages("stringr")

library(rvest)
library(magrittr)
library(stringr)
library(data.table)

###########################################################################

extractSingleMovieDetail <- function(url, pause){
  print(url)
  source.page <- read_html(url)
  #release year
  release_yr <- source.page %>% 
    html_nodes(".header .nobr") %>%  
    html_text() %>%
    str_replace_all("[^0-9]","")
  release_yr <- ifelse(length(release_yr)<1,NA,as.integer(release_yr[1]))
  
  #movie rating
  movie_rating <- source.page %>% 
    html_nodes("strong span") %>%  
    html_text()
  movie_rating <- ifelse(length(movie_rating)<1,NA,as.numeric(movie_rating[1]))
  
  #duration
  duration_mins <- source.page %>% 
    html_nodes("#overview-top time") %>%  
    html_text() %>%
    str_replace_all("[^0-9]","")
  duration_mins <- ifelse(length(duration_mins)<1,NA,as.numeric(duration_mins[1]))

  #ReleaseDate
  ReleaseDate <- source.page %>% 
    html_nodes(".infobar .nobr a") %>%  
    html_text()
  ReleaseDate <- ifelse(length(ReleaseDate)<1,NA,ReleaseDate[1])
  
  #MPAA rating
  MPAArating <- source.page %>% 
      html_nodes(".infobar") %>%  
      html_text()
  MPAArating <- str_extract(MPAArating,"(G|PG-13|PG 13|PG|R|NC-17|NC 17)")
  
  #genres
  genres <- source.page %>% 
    html_nodes(".infobar .itemprop") %>%  
    html_text()
  genre1 <- genres[1]
  genre2 <- genres[2]
  genre3 <- genres[3]
  
#   #NumImdbCriticReviews
#   numImdbCriticReviews <- source.page %>% 
#     html_nodes(".star-box-details a:nth-child(8) span") %>%  
#     html_text() %>% 
#     str_replace_all("[^0-9]","")
#   numImdbCriticReviews <- ifelse(length(numImdbCriticReviews)<1,NA,as.integer(numImdbCriticReviews))
  
  #Directors
  #detect Director Node
  directorNode7 <- source.page %>% 
    html_nodes("#overview-top .txt-block:nth-child(7)") %>%  
    html_text()
  if(length(directorNode7) > 0 && grepl(pattern="Director",x=directorNode7)){
    css_node <- "#overview-top .txt-block:nth-child(7) .itemprop"
    css_url <- "#overview-top .txt-block:nth-child(7) a"
  }  else{
    directorNode8 <- source.page %>% 
      html_nodes("#overview-top .txt-block:nth-child(8)") %>%  
      html_text()
    if(length(directorNode8) > 0 && grepl(pattern="Director",x=directorNode8)){
      css_node <- "#overview-top .txt-block:nth-child(8) .itemprop"
      css_url <- "#overview-top .txt-block:nth-child(8) a"
    }else{
      css_node <- "#overview-top .txt-block:nth-child(9) .itemprop"
      css_url <- "#overview-top .txt-block:nth-child(9) a"
    }
  }
  
  #DirectorName
  directorName <- source.page %>% 
    html_nodes(css_node) %>%  
    html_text()
  directorName <- ifelse(length(directorName)<1,NA,directorName)
  
  #DirectorURL and DirectorID
  directorURL <- source.page %>% 
    html_nodes(css_url)   
  directorURL <- directorURL[grepl(pattern="itemprop=\"name\"",x=directorURL)]
  directorURL <-  html_attr(directorURL,"href") %>%
    str_replace_all("\\?.*","")
  directorURL <- ifelse(is.na(directorURL[1]),NA,paste0('http://www.imdb.com',directorURL[1]))
  directorID <- str_replace_all(directorURL,'http://www.imdb.com/name/|/$',"")
  
  #Stars
  #detect stars node
  starsNode8 <- source.page %>% 
    html_nodes("#overview-top .txt-block:nth-child(8)") %>%  
    html_text()
  if(length(starsNode8)>0 && grepl(pattern="Stars:",x=starsNode8)){
    css_node <- "#overview-top :nth-child(8) .itemprop"
    css_url <- "#overview-top :nth-child(8) a"
  }  else{
    starsNode9 <- source.page %>% 
      html_nodes("#overview-top .txt-block:nth-child(9)") %>%  
      html_text()
      if(length(starsNode9)>0 && grepl(pattern="Stars:",x=starsNode9)){
        css_node <- "#overview-top :nth-child(9) .itemprop"
        css_url <- "#overview-top :nth-child(9) a"
      }else{
        css_node <- "#overview-top :nth-child(10) .itemprop"
        css_url <- "#overview-top :nth-child(10) a"
      }
  }
    
  stars <- source.page %>% 
    html_nodes(css_node) %>%  
    html_text()
  starsURLs <- source.page %>% 
    html_nodes(css_url) 
  starsURLs <- starsURLs[grepl(pattern="itemprop=\"name\"",x=starsURLs)]
  starsURLs <-  html_attr(starsURLs,"href") %>%
    str_replace_all("\\?.*","")
  starsURLs <- starsURLs[1:3]
  
  starsIds <- str_replace_all(starsURLs,'/name/|/$',"")
  star1Name <-  stars[1]
  star1Id <-  starsIds[1]
  star1URL <-  ifelse(is.na(starsURLs[1]),NA,paste0('http://www.imdb.com',starsURLs[1]))
  star2Name <-  stars[2]
  star2Id <-  starsIds[2]
  star2URL <-  ifelse(is.na(starsURLs[2]),NA,paste0('http://www.imdb.com',starsURLs[2]))
  star3Name <-  stars[3]
  star3Id <-  starsIds[3]
  star3URL <-  ifelse(is.na(starsURLs[3]),NA,paste0('http://www.imdb.com',starsURLs[3]))
  
  #NumOscarWins
  numOscarWins <- source.page %>% 
    html_nodes("#titleAwardsRanks b") %>%  
    html_text() %>% 
    str_replace_all("[^0-9]","")
  if(length(numOscarWins)==0){
    numOscarWins <- 0
  } else{
    numOscarWins <- c(as.integer(numOscarWins[1]))
  }
  
  # Get raw string data for box office info, country/language, aspect ratio
  strings <- html_text(html_nodes(source.page,"#titleDetails .txt-block"))
  flags <- c("Aspect Ratio","Country","Language","Budget","Opening Weekend","Gross")
  patterns <- c("[0-9\\.]+ ?: ?[0-9]+","[\\s]*Country:[\\s]*([a-zA-Z]+)[\\s]*",
                "[\\s]*Language:[\\s]*([a-zA-Z]+)[\\s]*","[^ ]+ ?[0-9,]+",
                "[^ ]+ ?[0-9,]+","[^ ]+ ?[0-9,]+")
  replacements <- c(NA,"\\1","\\1",NA,NA,NA,NA)
  # initialize list for the raw strings
  data = as.list(rep(NA,length(flags)))
  names(data) = flags
  # extract
  for(i in 1:length(flags)){
      flag = flags[i]
      pattern = patterns[i]
      replacement = replacements[i]
      index = which(str_detect(strings,flag))[1]
      string = strings[index]
      if(!is.na(index)){
          if(is.na(replacement)){
              data[[flag]] = str_extract(string, pattern)
          } else {
              data[[flag]] = str_replace(string, pattern, replacement)
          }
          
      }
  }
  # Unpack the box office strings
  budget <- str_replace_all(data[["Budget"]],"[^0-9]","")
  budget <- ifelse(length(budget)<1,NA,as.numeric(budget[1]))
  
  openweekend <- str_replace_all(data[["Opening Weekend"]],"[^0-9]","")
  openweekend <- ifelse(length(openweekend)<1,NA,as.numeric(openweekend[1]))
  
  gross <- str_replace_all(data[["Gross"]],"[^0-9]","")
  gross <- ifelse(length(gross)<1,NA,as.numeric(gross[1]))
  
  budgetCurr <- str_trim(str_extract(data[["Budget"]],"^[^0-9]+"))
  openweekendCurr <- str_trim(str_extract(data[["Opening Weekend"]],"^[^0-9]+"))
  grossCurr <- str_trim(str_extract(data[["Gross"]],"^[^0-9]+"))
  
  aspectRatio <- data[["Aspect Ratio"]]
  country <- data[["Country"]]
  language <- data[["Language"]]
  
  # Second pass at MPAA rating
  if(is.na(MPAArating)){
      strings <- html_text(html_nodes(source.page,"#titleStoryLine .txt-block"))
      index = which(str_detect(strings, "Rating"))
      if(!(length(index) == 0)){
          MPAArating = str_extract(strings[index], "Rated ([^ ]+)")
          MPAArating = str_replace(MPAArating, "Rated ([^ ]+)", "\\1")
      }
  }
  
  # Counts of user and critic ratings
  strings <- html_text(html_nodes(source.page,".star-box-details span"))
  
  index = which(str_detect(strings, "user"))
  MovieNumUserRatings = str_extract(strings[index], "[0-9]+")
  MovieNumUserRatings = ifelse(length(MovieNumUserRatings)<1,NA,as.integer(MovieNumUserRatings[1]))
  
  index = which(str_detect(strings, "critic"))
  MovieNumCriticRatings = str_extract(strings[index], "[0-9]+")
  MovieNumCriticRatings = ifelse(length(MovieNumCriticRatings)<1,NA,as.integer(MovieNumCriticRatings[1]))
  
#   #number of users who rated movie
#   MovieNumUserRatings <- source.page %>% 
#       html_nodes(".star-box-details a:nth-child(3) span") %>%  
#       html_text() %>%
#       str_replace_all("[^0-9]","")
#   MovieNumUserRatings <- ifelse(length(MovieNumUserRatings)<1,NA,as.integer(MovieNumUserRatings))
  
  returnList <- list(url, release_yr, movie_rating, MovieNumUserRatings, MovieNumCriticRatings,
                     duration_mins, aspectRatio, MPAArating,
                     country, language, ReleaseDate, genre1, genre2, genre3, #numImdbCriticReviews,
                    directorName, directorID, directorURL, star1Name, star1Id, star1URL,
                    star2Name, star2Id, star2URL, star3Name, star3Id, star3URL, 
                    budget, budgetCurr, openweekend, openweekendCurr, gross, grossCurr, numOscarWins)  
  names(returnList) = c("MovieURL","ReleaseYear", "IMDBRating","NumberOfUsersRated","NumberOfCriticsRated",
                        "DurationMins","AspectRatio",
                        "MPAARating","Country","Language","ReleaseDate","Genre1","Genre2","Genre3",#"NumIMDBCriticReviews",
                        "DirectorName","DirectorID","DirectorURL","Star1Name","Star1ID","Star1URL",
                        "Star2Name","Star2ID","Star2URL","Star3Name","Star3ID","Star3URL",
                        "BoxOfficeBudget","BoxOfficeBudgetCurr","BoxOfficeOpeningWeekend","BoxOfficeOpeningWeekendCurr",
                        "BoxOfficeGross","BoxOfficeGrossCurr","NumberOfOscars")
  # mean wait time of `pause` secs
  Sys.sleep(rgamma(1, 2*pause, 2))
  
  return(returnList)
}


extractMovieDetails <- function(mainPageData, chunksize = 100, startIndex = 1, 
                                endIndex = nrow(mainPageData), dataDir, pause = 1){
    urls <-  as.character(mainPage$MovieURL)
    if(missing(endIndex)){
        endIndex = nrow(mainPageData)
    }
    
    numberOfChunks <- ceiling((endIndex-startIndex+1)/chunksize)
    movieDetails <- list()
    length(movieDetails) <- numberOfChunks
    
    print(paste0("Extracting movies ",startIndex," to ",endIndex))
    
    for(i in 1:numberOfChunks){
        minIndex = (i - 1)*chunksize + 1
        maxIndex = min(minIndex + chunksize - 1, endIndex, length(urls))
        filename = paste0(dataDir,"movieDetails",minIndex,"to",maxIndex,".RData")
        
        print(filename)
        
        if(!file.exists(filename)){
            movieData <- lapply(urls[minIndex:maxIndex],extractSingleMovieDetail, pause = pause)
            movieData <- rbindlist(movieData)
            save(movieData, file = filename)
            movieDetails[[i]] <- movieData
        } else {
            load(file = filename)
            movieDetails[[i]] <- movieData
        }
        print("");print("")
    }
    movieDataFrame <- Reduce(rbind, movieDetails)
    
    return(movieDataFrame)
}
